### ISSUE TITLE
No callback to dismiss

### ISSUE THREAD

**Issue by purepure** [TimOliver/TOActionSheet#2]
No callback when user tap on background to dismiss action sheet. Please let me know If there is anyway to catch that event.

Thank

**Comment by TimOliver** [comment]
@Sjoerdjanssenen added this in a PR! I'll push it to CocoaPods in a moment, but it's live in the master branch now.

https://github.com/TimOliver/TOActionSheet/commit/9495eb059d39f4f33866948f9f3f2d89cb8ec065

Thanks everyone!
